### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by zanjs** [LeoAJ/react-iTunes-search#1]
zandeMacBook-Pro:react-iTunes-search juluad$ npm run dev

> react-iTunes-search@1.0.2 dev /Users/www/react/react-post/react-iTunes-search
> babel server.js | node

sh: babel: command not found

**Comment by zanjs** [comment]
npm install -g babel

**Comment by LeoAJ** [comment]
Thanks for the reporting! Added `babel` into `package.json`, should be fixed right now. Let me know if there is any other issue. Thanks again!
