### ISSUE TITLE
Debugging js code with debugger command in JS file

### ISSUE THREAD

**Issue by nazeels** [LeoAJ/react-iTunes-search#13]
Hey Leo

Thanks for the simple and straightforward example of ReactJS.

Can you please share any article or steps to follow, to debug the bundle.js file with chrome dev tools, especially with debugger command. Do I need to configure  any propery on webpack configuration?

**Comment by LeoAJ** [comment]
@nazeels 

You can set `devtool` to `inline-source-map` in order to debug in chrome dev tools in [here](https://github.com/LeoAJ/react-iTunes-search/blob/master/webpack/webpack.config.dev.js#L15), hope I answered your question, thanks for asking by the way.

**Comment by nazeels** [comment]
Thanks a lot
