### ISSUE TITLE
can't find /dist/build.js

### ISSUE THREAD

**Issue by SallyOne** [LeoAJ/react-iTunes-search#2]
this example use react-hot-loader and webpack-dev-server, but i can't find /dist/bundle.js, in browser can find this js,so what happe？

**Comment by LeoAJ** [comment]
`webpack-dev-server` will serve `bundle.js` on the fly automatically for you when you are running local development, so you will not see that file in your local directory, you can find more information from [webpack-dev-server](https://webpack.github.io/docs/webpack-dev-server.html)

**Comment by LeoAJ** [comment]
i will close the issue now, Thanks!
