### ISSUE TITLE
npm-cli.js "start" error

### ISSUE THREAD

**Issue by benpetersen** [LeoAJ/react-iTunes-search#3]
When starting the project v1.0.4 (2/3/2015)
Failed at the react-iTunes-search script 'babel-node server.js 
Exit status 1

[npm-debug.txt](https://github.com/LeoAJ/react-iTunes-search/files/116358/npm-debug.txt)

**Comment by LeoAJ** [comment]
Hi @benpetersen 

Can you try to delete the enitre `node-modules` folder and do `npm install`, see if it works? The reason maybe because the different version of babel. Should be able to fix to redo `npm install`. Let me know if it works. Thanks for reporting, appreciated.

**Comment by LeoAJ** [comment]
will close it, feel free to open any issue later on. Thanks!
