### ISSUE TITLE
api key

### ISSUE THREAD

**Issue by fredhampton** [LeoAJ/react-iTunes-search#4]
Is there a way to enter in our  itunes/apple api key?

Thanks

**Comment by LeoAJ** [comment]
[iTunes Search API](https://affiliate.itunes.apple.com/resources/documentation/itunes-store-web-service-search-api/) do not required API key to use it. Let me know if that helps, thanks!

**Comment by fredhampton** [comment]
I understand that no API key is needed but 
If we wanted to add our API key where in the code could we add it ?

Thanks so much for your help

 

On May 2, 2016 at 10:29:13 PM, Leo Hsieh (notifications@github.com) wrote:

iTunes Search API do not required API key to use it. Let me know if that helps, thanks!

**Comment by LeoAJ** [comment]
I see, for this one it was not designed for OAuth required API at first place, so it might not be easy to use this codebase to extend for that. You need to see how your API integrated with its keys and it may vary based on different API structure.

I had another [app](https://github.com/LeoAJ/react-facebook-friends) used Facebook API with app id, maybe that one can help you, thanks.

**Comment by fredhampton** [comment]
Ok… I see
Can you let me know in which file(s) I can find the url string that is passed to iTunes ?


Thanks !!!

 

On May 3, 2016 at 8:50:09 AM, Leo Hsieh (notifications@github.com) wrote:

I see, for this one it was not designed for OAuth required API at first place, so it might not be easy to use this codebase to extend for that. You need to see how your API integrated with its keys and it may vary based on different API structure.

I had another app used Facebook API with app id, maybe that one can help you, thanks.

**Comment by LeoAJ** [comment]
It is in the first table of iTunes Search API references.

**Comment by fredhampton** [comment]
Thanks !!!

 

On May 3, 2016 at 9:08:26 AM, Leo Hsieh (notifications@github.com) wrote:

It is in the first table of iTunes Search API references.

**Comment by LeoAJ** [comment]
No problem!
