### ISSUE TITLE
Start and Stop App

### ISSUE THREAD

**Issue by fredhampton** [LeoAJ/react-iTunes-search#5]
We need to make some changes to extend the app.
How can we start and stop the app/service so that he changes are saved and recognized 

Thanks

**Comment by LeoAJ** [comment]
Sorry I am not quite follow the question.

**Comment by fredhampton** [comment]
Its ok i figured it out 


Thanks 

 

On May 4, 2016 at 1:36:11 PM, Leo Hsieh (notifications@github.com) wrote:

Sorry I am not quite follow the question.

**Comment by fredhampton** [comment]
Is there a way to have the page start with search query results ? …..I would like the page to start with the results for jimi hendrix instead of the black page 


Thanks

 

On May 4, 2016 at 1:37:04 PM, william Dyson (william@ida.coop) wrote:

Its ok i figured it out 


Thanks 

 

On May 4, 2016 at 1:36:11 PM, Leo Hsieh (notifications@github.com) wrote:

Sorry I am not quite follow the question.

**Comment by LeoAJ** [comment]
You can extract `search` function out of emitter listener from `Container` component like this.

```js
  search = ({ query, media = 'all' }) => {
    reqwest({
      url: `https://itunes.apple.com/search?media=${getMedia(media || 'all')}&term=${query.split(' ').join('+')}`,
      type: 'jsonp'
    })
    .then(response => this.setState({ response, type: response.resultCount || 'noContent' }))
    .fail(err => this.setState({ type: 'error' }));
  };
```

and initial your first search in `componentDidMount` like this
```js
componentDidMount = () => {
    // first search
    this.search({ query: 'jimi hendrix' });
    emitter.on('search', (state) => {
      this.setState({ type: 'loading' });
      this.search(state);
    });
  };
```

remember to set state to `loading` when page loads initially.

**Comment by fredhampton** [comment]
Thanks !!!!!!!!!!!!!!!

 

On May 4, 2016 at 3:53:52 PM, Leo Hsieh (notifications@github.com) wrote:

You can extract search function out of emitter listener from Container component like this.

  search = ({ query, media = 'all' }) => {
    reqwest({
      url: `https://itunes.apple.com/search?media=${getMedia(media || 'all')}&term=${query.split(' ').join('+')}`,
      type: 'jsonp'
    })
    .then(response => this.setState({ response, type: response.resultCount || 'noContent' }))
    .fail(err => this.setState({ type: 'error' }));
  };
and initial your first search in componentDidMount like this

componentDidMount = () => {
    // first search
    this.search({ query: 'jimi hendrix' });
    emitter.on('search', (state) => {
      this.setState({ type: 'loading' });
      this.search(state);
    });
  };
remember to set state to loading when page loads initially.

**Comment by fredhampton** [comment]
After I make changes to the code how to I start and stop the service so that the changes take effect ?


Thanks


 

On May 4, 2016 at 3:53:52 PM, Leo Hsieh (notifications@github.com) wrote:

You can extract search function out of emitter listener from Container component like this.

  search = ({ query, media = 'all' }) => {
    reqwest({
      url: `https://itunes.apple.com/search?media=${getMedia(media || 'all')}&term=${query.split(' ').join('+')}`,
      type: 'jsonp'
    })
    .then(response => this.setState({ response, type: response.resultCount || 'noContent' }))
    .fail(err => this.setState({ type: 'error' }));
  };
and initial your first search in componentDidMount like this

componentDidMount = () => {
    // first search
    this.search({ query: 'jimi hendrix' });
    emitter.on('search', (state) => {
      this.setState({ type: 'loading' });
      this.search(state);
    });
  };
remember to set state to loading when page loads initially.

**Comment by fredhampton** [comment]
This is what I have in my Container.js file …..Can you let me know if this is correct to have Jimi Hendrix search results populate the start page ?

import React, { Component } from 'react';
import List from './List';
import Message from './Message';
import emitter from '../emitter';
import reqwest from 'reqwest';
import { getMedia } from '../utils';

class Container extends Component {

  state = {
    type: 'start'
  };

  componentDidMount = () => {
    // first search
    this.search({ query: 'jimi hendrix' });
    emitter.on('search', (state) => {
      this.setState({ type: 'loading' });
      this.search(state);
    });
  };
 search = ({ query, media = 'all' }) => {
    reqwest({
      url: `https://itunes.apple.com/search?media=${getMedia(media || 'all')}&term=${query.split(' ').join('+')}`,
      type: 'jsonp'
    })
    .then(response => this.setState({ response, type: response.resultCount || 'noContent' }))
    .fail(err => this.setState({ type: 'error' }));
  componentWillUnmount = () => {
    emitter.removeListener('search');
  };

 

On May 4, 2016 at 3:53:52 PM, Leo Hsieh (notifications@github.com) wrote:

You can extract search function out of emitter listener from Container component like this.

  search = ({ query, media = 'all' }) => {
    reqwest({
      url: `https://itunes.apple.com/search?media=${getMedia(media || 'all')}&term=${query.split(' ').join('+')}`,
      type: 'jsonp'
    })
    .then(response => this.setState({ response, type: response.resultCount || 'noContent' }))
    .fail(err => this.setState({ type: 'error' }));
  };
and initial your first search in componentDidMount like this

componentDidMount = () => {
    // first search
    this.search({ query: 'jimi hendrix' });
    emitter.on('search', (state) => {
      this.setState({ type: 'loading' });
      this.search(state);
    });
  };
remember to set state to loading when page loads initially.
